import { Sparkles, FileText } from "lucide-react";
import type { Summary, SummarySection } from "../types";
import { clockTime } from "../utils/format";

export function ExplanationBlock({ sections, compact = false }: { sections: SummarySection; compact?: boolean }) {
  const rows: { title: string; body: string; tone: string; tag: string }[] = [
    { title: "What's happening", body: sections.whats_happening, tone: "var(--text)", tag: "Observed" },
    { title: "Why it may matter", body: sections.why_it_matters, tone: "var(--text)", tag: "Impact" },
    { title: "Possible connection", body: sections.possible_connection, tone: "#e9d5ff", tag: "Not a confirmed cause" },
  ];
  return (
    <div className={compact ? "space-y-2.5" : "space-y-3"}>
      {rows.map((r) => (
        <section key={r.title}>
          <div className="mb-0.5 flex items-center justify-between gap-2">
            <h3 className="label-caps">{r.title}</h3>
            <span className="text-[10px] text-[var(--faint)]">{r.tag}</span>
          </div>
          <p className="text-[13px] leading-relaxed" style={{ color: r.tone }}>
            {r.body}
          </p>
        </section>
      ))}
    </div>
  );
}

export function SourceTag({ by, at, note }: { by: "template" | "ai"; at?: string; note?: string | null }) {
  const ai = by === "ai";
  const Icon = ai ? Sparkles : FileText;
  return (
    <span
      className="inline-flex items-center gap-1 rounded-md px-1.5 py-0.5 text-[10px] font-medium"
      style={{ background: "var(--panel-2)", color: ai ? "#d8b4fe" : "var(--muted)", border: "1px solid var(--line)" }}
      title={
        note ??
        (ai
          ? "Plain-language wording by an AI model, generated only from CityPulse's analysed data and checked automatically."
          : "Generated by fixed rules directly from the analysed data.")
      }
    >
      <Icon size={11} aria-hidden />
      {ai ? "AI-assisted" : "Rule-based"}
      {at && <span className="text-[var(--faint)]">· {clockTime(at, false)}</span>}
    </span>
  );
}

export function SummaryPanel({ summary }: { summary: Summary }) {
  return (
    <div className="panel p-4" aria-live="polite">
      <div className="mb-2 flex items-center justify-between">
        <h2 className="label-caps" style={{ color: "var(--pulse)" }}>
          Right now
        </h2>
        <SourceTag by={summary.generated_by} at={summary.generated_at} note={summary.note} />
      </div>
      <p className="mb-3 text-[17px] font-semibold leading-snug">{summary.headline}</p>
      <ExplanationBlock sections={summary.sections} compact />
    </div>
  );
}
